unit_tests: &unit_tests
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: NPM Rebuild
        command: npm rebuild
    - run:
        name: Run unit tests.
        command: npm run ci:test
canary_tests: &canary_tests
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: NPM Rebuild
        command: npm rebuild
    - run:
        name: Install Webpack Canary
        command: npm i --no-save webpack@next
    - run:
        name: Run unit tests.
        command: npm run ci:test

version: 2
jobs:
  dependency_cache:
    docker:
      - image: webpackcontrib/circleci-node-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  node8_webpack_latest:
    docker:
      - image: webpackcontrib/circleci-node8:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Rebuild
          command: npm rebuild
      - run:
          name: Run unit tests.
          command: npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  node6_webpack_latest:
    docker:
      - image: webpackcontrib/circleci-node6:latest
    <<: *unit_tests
  node9_webpack_latest:
    docker:
      - image: webpackcontrib/circleci-node9:latest
    <<: *unit_tests
  node8_webpack_canary:
    docker:
      - image: webpackcontrib/circleci-node8:latest
    <<: *canary_tests
  analysis:
    docker:
      - image: webpackcontrib/circleci-node-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Rebuild
          command: npm rebuild
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run NSP Security Check.
          command: npm run security
      - run:
          name: Validate Commit Messages
          command: npm run ci:lint:commits
  publish:
    docker:
      - image: webpackcontrib/circleci-node-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Rebuild
          command: npm rebuild
      - run:
          name: Validate Commit Messages
          command: npm run release:validate
      - run:
          name: Publish to NPM
          command: printf "noop running conventional-github-releaser"

version: 2.0
workflows:
  version: 2
  validate-publish:
    jobs:
      - dependency_cache
      - node6_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node8_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node9_webpack_latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node8_webpack_canary:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - analysis:
          requires:
            - node6_webpack_latest
            - node8_webpack_latest
            - node9_webpack_latest
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - node6_webpack_latest
            - node8_webpack_latest
            - node9_webpack_latest
            - analysis
          filters:
            branches:
              only:
                - master
